### ISSUE TITLE
[BUG] When installing 1.12.2

### ISSUE THREAD

**Issue by Ochaun** [Ochaun/LastLog4jDemo#1]
Older versions of minecraft can't find the primary display or the OpenGL configuration. The only graphics customizations for this box are vbox guest editions and a gnome preinstall. Stacktrace from Minecraft: 
```
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 7/13/22 10:19 AM
Description: Initializing game

java.lang.ExceptionInInitializerError
        at bib.av(SourceFile:661)
        at bib.aq(SourceFile:456)
        at bib.a(SourceFile:404)
        at net.minecraft.client.main.Main.main(SourceFile:123)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
        at org.lwjgl.opengl.XRandR.findPrimary(XRandR.java:326)
        at org.lwjgl.opengl.XRandR.ScreentoDisplayMode(XRandR.java:315)
        at org.lwjgl.opengl.LinuxDisplay$3.run(LinuxDisplay.java:746)
        at org.lwjgl.opengl.LinuxDisplay$3.run(LinuxDisplay.java:743)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:743)
        at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
        ... 4 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
        at bib.av(SourceFile:661)
        at bib.aq(SourceFile:456)
-- Initialization --
Details:
Stacktrace:
        at bib.a(SourceFile:404)
        at net.minecraft.client.main.Main.main(SourceFile:123)

-- System Details --
Details:
        Minecraft Version: 1.12.2
        Operating System: Linux (amd64) version 4.15.0-188-generic
        Java Version: 1.8.0_202, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 68636112 bytes (65 MB) / 134217728 bytes (128 MB) up to 2147483648 bytes (2048 MB)
        JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
        IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
        Launched Version: 1.12.2
        LWJGL: 2.9.4
        OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
        GL Caps:
        Using VBOs: Yes
        Is Modded: Probably not. Jar signature remains and client brand is untouched.
        Type: Client (map_client.txt)
        Resource Packs:
        Current Language: ~~ERROR~~ NullPointerException: null
        Profiler Position: N/A (disabled)
        CPU: <unknown>

```

**Comment by Ochaun** [comment]
```bash
vagrant@ubuntu-bionic:~$ startx


X.Org X Server 1.19.6
Release Date: 2017-12-20
X Protocol Version 11, Revision 0
Build Operating System: Linux 5.4.0-121-generic x86_64 Ubuntu
Current Operating System: Linux ubuntu-bionic 4.15.0-188-generic #199-Ubuntu SMP Wed Jun 15 20:42:56 UTC 2022 x86_64
Kernel command line: BOOT_IMAGE=/boot/vmlinuz-4.15.0-188-generic root=LABEL=cloudimg-rootfs ro console=tty1 console=ttyS0
Build Date: 07 July 2022  05:11:20PM
xorg-server 2:1.19.6-1ubuntu4.11 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.34.0
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/home/vagrant/.local/share/xorg/Xorg.1.log", Time: Mon Jul 18 15:14:38 2022
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) parse_vt_settings: Cannot open /dev/tty0 (Permission denied)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/home/vagrant/.local/share/xorg/Xorg.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
^[[Bxinit: giving up
xinit: unable to connect to X server: Connection refused
xinit: server error
Couldn't get a file descriptor referring to the console
```
```bash
vagrant@ubuntu-bionic:~$ cat .local/share/xorg/Xorg.1.log 
[   881.971] 
X.Org X Server 1.19.6
Release Date: 2017-12-20
[   881.971] X Protocol Version 11, Revision 0
[   881.971] Build Operating System: Linux 5.4.0-121-generic x86_64 Ubuntu
[   881.971] Current Operating System: Linux ubuntu-bionic 4.15.0-188-generic #199-Ubuntu SMP Wed Jun 15 20:42:56 UTC 2022 x86_64
[   881.971] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-4.15.0-188-generic root=LABEL=cloudimg-rootfs ro console=tty1 console=ttyS0
[   881.971] Build Date: 07 July 2022  05:11:20PM
[   881.971] xorg-server 2:1.19.6-1ubuntu4.11 (For technical support please see http://www.ubuntu.com/support) 
[   881.971] Current version of pixman: 0.34.0
[   881.971] 	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
[   881.971] Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[   881.971] (==) Log file: "/home/vagrant/.local/share/xorg/Xorg.1.log", Time: Mon Jul 18 15:14:38 2022
[   881.971] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[   881.972] (==) No Layout section.  Using the first Screen section.
[   881.972] (==) No screen section available. Using defaults.
[   881.972] (**) |-->Screen "Default Screen Section" (0)
[   881.972] (**) |   |-->Monitor "<default monitor>"
[   881.972] (==) No monitor specified for screen "Default Screen Section".
	Using a default monitor configuration.
[   881.972] (==) Automatically adding devices
[   881.972] (==) Automatically enabling devices
[   881.972] (==) Automatically adding GPU devices
[   881.972] (==) Automatically binding GPU devices
[   881.972] (==) Max clients allowed: 256, resource mask: 0x1fffff
[   881.972] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[   881.972] 	Entry deleted from font path.
[   881.972] (WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[   881.972] 	Entry deleted from font path.
[   881.972] (WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[   881.972] 	Entry deleted from font path.
[   881.972] (WW) The directory "/usr/share/fonts/X11/Type1" does not exist.
[   881.972] 	Entry deleted from font path.
[   881.972] (WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[   881.972] 	Entry deleted from font path.
[   881.972] (WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[   881.972] 	Entry deleted from font path.
[   881.972] (==) FontPath set to:
	/usr/share/fonts/X11/misc,
	built-ins
[   881.972] (==) ModulePath set to "/usr/lib/xorg/modules"
[   881.972] (II) The server relies on udev to provide the list of input devices.
	If no devices become available, reconfigure udev or disable AutoAddDevices.
[   881.972] (II) Loader magic: 0x5580dcdac020
[   881.972] (II) Module ABI versions:
[   881.972] 	X.Org ANSI C Emulation: 0.4
[   881.972] 	X.Org Video Driver: 23.0
[   881.972] 	X.Org XInput driver : 24.1
[   881.972] 	X.Org Server Extension : 10.0
[   881.974] (EE) systemd-logind: failed to get session: PID 18179 does not belong to any known session
[   881.974] (II) xfree86: Adding drm device (/dev/dri/card0)
[   881.974] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied
[   881.976] (--) PCI:*(0:0:2:0) 80ee:beef:0000:0000 rev 0, Mem @ 0xe0000000/16777216, BIOS @ 0x????????/131072
[   881.976] (II) LoadModule: "glx"
[   881.976] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[   881.977] (II) Module glx: vendor="X.Org Foundation"
[   881.977] 	compiled for 1.19.6, module version = 1.0.0
[   881.977] 	ABI class: X.Org Server Extension, version 10.0
[   881.977] (==) Matched vboxvideo as autoconfigured driver 0
[   881.977] (==) Matched modesetting as autoconfigured driver 1
[   881.977] (==) Matched fbdev as autoconfigured driver 2
[   881.978] (==) Matched vesa as autoconfigured driver 3
[   881.978] (==) Assigned the driver to the xf86ConfigLayout
[   881.978] (II) LoadModule: "vboxvideo"
[   881.978] (WW) Warning, couldn't open module vboxvideo
[   881.978] (II) UnloadModule: "vboxvideo"
[   881.978] (II) Unloading vboxvideo
[   881.978] (EE) Failed to load module "vboxvideo" (module does not exist, 0)
[   881.978] (II) LoadModule: "modesetting"
[   881.978] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[   881.978] (II) Module modesetting: vendor="X.Org Foundation"
[   881.978] 	compiled for 1.19.6, module version = 1.19.6
[   881.978] 	Module class: X.Org Video Driver
[   881.978] 	ABI class: X.Org Video Driver, version 23.0
[   881.978] (II) LoadModule: "fbdev"
[   881.978] (WW) Warning, couldn't open module fbdev
[   881.978] (II) UnloadModule: "fbdev"
[   881.978] (II) Unloading fbdev
[   881.978] (EE) Failed to load module "fbdev" (module does not exist, 0)
[   881.978] (II) LoadModule: "vesa"
[   881.978] (WW) Warning, couldn't open module vesa
[   881.978] (II) UnloadModule: "vesa"
[   881.978] (II) Unloading vesa
[   881.978] (EE) Failed to load module "vesa" (module does not exist, 0)
[   881.978] (==) Matched vboxvideo as autoconfigured driver 0
[   881.978] (==) Matched modesetting as autoconfigured driver 1
[   881.978] (==) Matched fbdev as autoconfigured driver 2
[   881.978] (==) Matched vesa as autoconfigured driver 3
[   881.978] (==) Assigned the driver to the xf86ConfigLayout
[   881.978] (II) LoadModule: "vboxvideo"
[   881.978] (WW) Warning, couldn't open module vboxvideo
[   881.978] (II) UnloadModule: "vboxvideo"
[   881.978] (II) Unloading vboxvideo
[   881.978] (EE) Failed to load module "vboxvideo" (module does not exist, 0)
[   881.978] (II) LoadModule: "modesetting"
[   881.978] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[   881.978] (II) Module modesetting: vendor="X.Org Foundation"
[   881.978] 	compiled for 1.19.6, module version = 1.19.6
[   881.978] 	Module class: X.Org Video Driver
[   881.978] 	ABI class: X.Org Video Driver, version 23.0
[   881.978] (II) UnloadModule: "modesetting"
[   881.978] (II) Unloading modesetting
[   881.978] (II) Failed to load module "modesetting" (already loaded, 0)
[   881.978] (II) LoadModule: "fbdev"
[   881.978] (WW) Warning, couldn't open module fbdev
[   881.978] (II) UnloadModule: "fbdev"
[   881.978] (II) Unloading fbdev
[   881.978] (EE) Failed to load module "fbdev" (module does not exist, 0)
[   881.978] (II) LoadModule: "vesa"
[   881.979] (WW) Warning, couldn't open module vesa
[   881.979] (II) UnloadModule: "vesa"
[   881.979] (II) Unloading vesa
[   881.979] (EE) Failed to load module "vesa" (module does not exist, 0)
[   881.979] (II) modesetting: Driver for Modesetting Kernel Drivers: kms
[   881.979] (EE) 
Fatal server error:
[   881.979] (EE) parse_vt_settings: Cannot open /dev/tty0 (Permission denied)
[   881.979] (EE) 
[   881.979] (EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
[   881.979] (EE) Please also check the log file at "/home/vagrant/.local/share/xorg/Xorg.1.log" for additional information.
[   881.979] (EE) 
[   881.979] (WW) xf86CloseConsole: KDSETMODE failed: Bad file descriptor
[   881.979] (WW) xf86CloseConsole: VT_GETMODE failed: Bad file descriptor
[   881.979] (EE) Server terminated with error (1). Closing log file.
```
